export const countries = [ 
    {item: 'Afghanistan', value: 'AF'}, 
    {item: 'Åland Islands', value: 'AX'}, 
    {item: 'Albania', value: 'AL'}, 
    {item: 'Algeria', value: 'DZ'}, 
    {item: 'American Samoa', value: 'AS'}, 
    {item: 'AndorrA', value: 'AD'}, 
    {item: 'Angola', value: 'AO'}, 
    {item: 'Anguilla', value: 'AI'}, 
    {item: 'Antarctica', value: 'AQ'}, 
    {item: 'Antigua and Barbuda', value: 'AG'}, 
    {item: 'Argentina', value: 'AR'}, 
    {item: 'Armenia', value: 'AM'}, 
    {item: 'Aruba', value: 'AW'}, 
    {item: 'Australia', value: 'AU'}, 
    {item: 'Austria', value: 'AT'}, 
    {item: 'Azerbaijan', value: 'AZ'}, 
    {item: 'Bahamas', value: 'BS'}, 
    {item: 'Bahrain', value: 'BH'}, 
    {item: 'Bangladesh', value: 'BD'}, 
    {item: 'Barbados', value: 'BB'}, 
    {item: 'Belarus', value: 'BY'}, 
    {item: 'Belgium', value: 'BE'}, 
    {item: 'Belize', value: 'BZ'}, 
    {item: 'Benin', value: 'BJ'}, 
    {item: 'Bermuda', value: 'BM'}, 
    {item: 'Bhutan', value: 'BT'}, 
    {item: 'Bolivia', value: 'BO'}, 
    {item: 'Bosnia and Herzegovina', value: 'BA'}, 
    {item: 'Botswana', value: 'BW'}, 
    {item: 'Bouvet Island', value: 'BV'}, 
    {item: 'Brazil', value: 'BR'}, 
    {item: 'British Indian Ocean Territory', value: 'IO'}, 
    {item: 'Brunei Darussalam', value: 'BN'}, 
    {item: 'Bulgaria', value: 'BG'}, 
    {item: 'Burkina Faso', value: 'BF'}, 
    {item: 'Burundi', value: 'BI'}, 
    {item: 'Cambodia', value: 'KH'}, 
    {item: 'Cameroon', value: 'CM'}, 
    {item: 'Canada', value: 'CA'}, 
    {item: 'Cape Verde', value: 'CV'}, 
    {item: 'Cayman Islands', value: 'KY'}, 
    {item: 'Central African Republic', value: 'CF'}, 
    {item: 'Chad', value: 'TD'}, 
    {item: 'Chile', value: 'CL'}, 
    {item: 'China', value: 'CN'}, 
    {item: 'Christmas Island', value: 'CX'}, 
    {item: 'Cocos (Keeling) Islands', value: 'CC'}, 
    {item: 'Colombia', value: 'CO'}, 
    {item: 'Comoros', value: 'KM'}, 
    {item: 'Congo', value: 'CG'}, 
    {item: 'Congo, The Democratic Republic of the', value: 'CD'}, 
    {item: 'Cook Islands', value: 'CK'}, 
    {item: 'Costa Rica', value: 'CR'}, 
    {item: 'Cote D\'Ivoire', value: 'CI'}, 
    {item: 'Croatia', value: 'HR'}, 
    {item: 'Cuba', value: 'CU'}, 
    {item: 'Cyprus', value: 'CY'}, 
    {item: 'Czech Republic', value: 'CZ'}, 
    {item: 'Denmark', value: 'DK'}, 
    {item: 'Djibouti', value: 'DJ'}, 
    {item: 'Dominica', value: 'DM'}, 
    {item: 'Dominican Republic', value: 'DO'}, 
    {item: 'Ecuador', value: 'EC'}, 
    {item: 'Egypt', value: 'EG'}, 
    {item: 'El Salvador', value: 'SV'}, 
    {item: 'Equatorial Guinea', value: 'GQ'}, 
    {item: 'Eritrea', value: 'ER'}, 
    {item: 'Estonia', value: 'EE'}, 
    {item: 'Ethiopia', value: 'ET'}, 
    {item: 'Falkland Islands (Malvinas)', value: 'FK'}, 
    {item: 'Faroe Islands', value: 'FO'}, 
    {item: 'Fiji', value: 'FJ'}, 
    {item: 'Finland', value: 'FI'}, 
    {item: 'France', value: 'FR'}, 
    {item: 'French Guiana', value: 'GF'}, 
    {item: 'French Polynesia', value: 'PF'}, 
    {item: 'French Southern Territories', value: 'TF'}, 
    {item: 'Gabon', value: 'GA'}, 
    {item: 'Gambia', value: 'GM'}, 
    {item: 'Georgia', value: 'GE'}, 
    {item: 'Germany', value: 'DE'}, 
    {item: 'Ghana', value: 'GH'}, 
    {item: 'Gibraltar', value: 'GI'}, 
    {item: 'Greece', value: 'GR'}, 
    {item: 'Greenland', value: 'GL'}, 
    {item: 'Grenada', value: 'GD'}, 
    {item: 'Guadeloupe', value: 'GP'}, 
    {item: 'Guam', value: 'GU'}, 
    {item: 'Guatemala', value: 'GT'}, 
    {item: 'Guernsey', value: 'GG'}, 
    {item: 'Guinea', value: 'GN'}, 
    {item: 'Guinea-Bissau', value: 'GW'}, 
    {item: 'Guyana', value: 'GY'}, 
    {item: 'Haiti', value: 'HT'}, 
    {item: 'Heard Island and Mcdonald Islands', value: 'HM'}, 
    {item: 'Holy See (Vatican City State)', value: 'VA'}, 
    {item: 'Honduras', value: 'HN'}, 
    {item: 'Hong Kong', value: 'HK'}, 
    {item: 'Hungary', value: 'HU'}, 
    {item: 'Iceland', value: 'IS'}, 
    {item: 'India', value: 'IN'}, 
    {item: 'Indonesia', value: 'ID'}, 
    {item: 'Iran, Islamic Republic Of', value: 'IR'}, 
    {item: 'Iraq', value: 'IQ'}, 
    {item: 'Ireland', value: 'IE'}, 
    {item: 'Isle of Man', value: 'IM'}, 
    {item: 'Israel', value: 'IL'}, 
    {item: 'Italy', value: 'IT'}, 
    {item: 'Jamaica', value: 'JM'}, 
    {item: 'Japan', value: 'JP'}, 
    {item: 'Jersey', value: 'JE'}, 
    {item: 'Jordan', value: 'JO'}, 
    {item: 'Kazakhstan', value: 'KZ'}, 
    {item: 'Kenya', value: 'KE'}, 
    {item: 'Kiribati', value: 'KI'}, 
    {item: 'Korea, Democratic People\'S Republic of', value: 'KP'}, 
    {item: 'Korea, Republic of', value: 'KR'}, 
    {item: 'Kuwait', value: 'KW'}, 
    {item: 'Kyrgyzstan', value: 'KG'}, 
    {item: 'Lao People\'S Democratic Republic', value: 'LA'}, 
    {item: 'Latvia', value: 'LV'}, 
    {item: 'Lebanon', value: 'LB'}, 
    {item: 'Lesotho', value: 'LS'}, 
    {item: 'Liberia', value: 'LR'}, 
    {item: 'Libyan Arab Jamahiriya', value: 'LY'}, 
    {item: 'Liechtenstein', value: 'LI'}, 
    {item: 'Lithuania', value: 'LT'}, 
    {item: 'Luxembourg', value: 'LU'}, 
    {item: 'Macao', value: 'MO'}, 
    {item: 'Macedonia, The Former Yugoslav Republic of', value: 'MK'}, 
    {item: 'Madagascar', value: 'MG'}, 
    {item: 'Malawi', value: 'MW'}, 
    {item: 'Malaysia', value: 'MY'}, 
    {item: 'Maldives', value: 'MV'}, 
    {item: 'Mali', value: 'ML'}, 
    {item: 'Malta', value: 'MT'}, 
    {item: 'Marshall Islands', value: 'MH'}, 
    {item: 'Martinique', value: 'MQ'}, 
    {item: 'Mauritania', value: 'MR'}, 
    {item: 'Mauritius', value: 'MU'}, 
    {item: 'Mayotte', value: 'YT'}, 
    {item: 'Mexico', value: 'MX'}, 
    {item: 'Micronesia, Federated States of', value: 'FM'}, 
    {item: 'Moldova, Republic of', value: 'MD'}, 
    {item: 'Monaco', value: 'MC'}, 
    {item: 'Mongolia', value: 'MN'}, 
    {item: 'Montserrat', value: 'MS'}, 
    {item: 'Morocco', value: 'MA'}, 
    {item: 'Mozambique', value: 'MZ'}, 
    {item: 'Myanmar', value: 'MM'}, 
    {item: 'Namibia', value: 'NA'}, 
    {item: 'Nauru', value: 'NR'}, 
    {item: 'Nepal', value: 'NP'}, 
    {item: 'Netherlands', value: 'NL'}, 
    {item: 'Netherlands Antilles', value: 'AN'}, 
    {item: 'New Caledonia', value: 'NC'}, 
    {item: 'New Zealand', value: 'NZ'}, 
    {item: 'Nicaragua', value: 'NI'}, 
    {item: 'Niger', value: 'NE'}, 
    {item: 'Nigeria', value: 'NG'}, 
    {item: 'Niue', value: 'NU'}, 
    {item: 'Norfolk Island', value: 'NF'}, 
    {item: 'Northern Mariana Islands', value: 'MP'}, 
    {item: 'Norway', value: 'NO'}, 
    {item: 'Oman', value: 'OM'}, 
    {item: 'Pakistan', value: 'PK'}, 
    {item: 'Palau', value: 'PW'}, 
    {item: 'Palestinian Territory, Occupied', value: 'PS'}, 
    {item: 'Panama', value: 'PA'}, 
    {item: 'Papua New Guinea', value: 'PG'}, 
    {item: 'Paraguay', value: 'PY'}, 
    {item: 'Peru', value: 'PE'}, 
    {item: 'Philippines', value: 'PH'}, 
    {item: 'Pitcairn', value: 'PN'}, 
    {item: 'Poland', value: 'PL'}, 
    {item: 'Portugal', value: 'PT'}, 
    {item: 'Puerto Rico', value: 'PR'}, 
    {item: 'Qatar', value: 'QA'}, 
    {item: 'Reunion', value: 'RE'}, 
    {item: 'Romania', value: 'RO'}, 
    {item: 'Russian Federation', value: 'RU'}, 
    {item: 'RWANDA', value: 'RW'}, 
    {item: 'Saint Helena', value: 'SH'}, 
    {item: 'Saint Kitts and Nevis', value: 'KN'}, 
    {item: 'Saint Lucia', value: 'LC'}, 
    {item: 'Saint Pierre and Miquelon', value: 'PM'}, 
    {item: 'Saint Vincent and the Grenadines', value: 'VC'}, 
    {item: 'Samoa', value: 'WS'}, 
    {item: 'San Marino', value: 'SM'}, 
    {item: 'Sao Tome and Principe', value: 'ST'}, 
    {item: 'Saudi Arabia', value: 'SA'}, 
    {item: 'Senegal', value: 'SN'}, 
    {item: 'Serbia and Montenegro', value: 'CS'}, 
    {item: 'Seychelles', value: 'SC'}, 
    {item: 'Sierra Leone', value: 'SL'}, 
    {item: 'Singapore', value: 'SG'}, 
    {item: 'Slovakia', value: 'SK'}, 
    {item: 'Slovenia', value: 'SI'}, 
    {item: 'Solomon Islands', value: 'SB'}, 
    {item: 'Somalia', value: 'SO'}, 
    {item: 'South Africa', value: 'ZA'}, 
    {item: 'South Georgia and the South Sandwich Islands', value: 'GS'}, 
    {item: 'Spain', value: 'ES'}, 
    {item: 'Sri Lanka', value: 'LK'}, 
    {item: 'Sudan', value: 'SD'}, 
    {item: 'Suriitem', value: 'SR'}, 
    {item: 'Svalbard and Jan Mayen', value: 'SJ'}, 
    {item: 'Swaziland', value: 'SZ'}, 
    {item: 'Sweden', value: 'SE'}, 
    {item: 'Switzerland', value: 'CH'}, 
    {item: 'Syrian Arab Republic', value: 'SY'}, 
    {item: 'Taiwan, Province of China', value: 'TW'}, 
    {item: 'Tajikistan', value: 'TJ'}, 
    {item: 'Tanzania, United Republic of', value: 'TZ'}, 
    {item: 'Thailand', value: 'TH'}, 
    {item: 'Timor-Leste', value: 'TL'}, 
    {item: 'Togo', value: 'TG'}, 
    {item: 'Tokelau', value: 'TK'}, 
    {item: 'Tonga', value: 'TO'}, 
    {item: 'Trinidad and Tobago', value: 'TT'}, 
    {item: 'Tunisia', value: 'TN'}, 
    {item: 'Turkey', value: 'TR'}, 
    {item: 'Turkmenistan', value: 'TM'}, 
    {item: 'Turks and Caicos Islands', value: 'TC'}, 
    {item: 'Tuvalu', value: 'TV'}, 
    {item: 'Uganda', value: 'UG'}, 
    {item: 'Ukraine', value: 'UA'}, 
    {item: 'United Arab Emirates', value: 'AE'}, 
    {item: 'United Kingdom', value: 'GB'}, 
    {item: 'United States', value: 'US'}, 
    {item: 'United States Minor Outlying Islands', value: 'UM'}, 
    {item: 'Uruguay', value: 'UY'}, 
    {item: 'Uzbekistan', value: 'UZ'}, 
    {item: 'Vanuatu', value: 'VU'}, 
    {item: 'Venezuela', value: 'VE'}, 
    {item: 'Viet Nam', value: 'VN'}, 
    {item: 'Virgin Islands, British', value: 'VG'}, 
    {item: 'Virgin Islands, U.S.', value: 'VI'}, 
    {item: 'Wallis and Futuna', value: 'WF'}, 
    {item: 'Western Sahara', value: 'EH'}, 
    {item: 'Yemen', value: 'YE'}, 
    {item: 'Zambia', value: 'ZM'}, 
    {item: 'Zimbabwe', value: 'ZW'} 
  ]