const data = [
  {
    id: 1,
    title: "test 1",
    details: "Lorem ipsum dolor sit amet consectetur",
    description: "Lorem ipsum dolor sit amet consectetur",
    assignee: "Metin",
    date: "May 29, 2023 @ 23:26:44",
    rule: "Enumaration of Users",
    severity: "low",
    type: "Malware Attack",
  },
  {
    id: 2,
    title: "test 2",
    details: "Lorem ipsum dolor sit amet consectetur",
    description: "Lorem ipsum dolor sit amet consectetur",
    assignee: "Charles Carmichael",
    date: "May 29, 2023 @ 23:26:44",
    rule: "Enumaration of Users",
    severity: "low",
    type: "Malware Attack",
  },
  {
    id: 3,
    title: "test 3",
    details: "Lorem ipsum dolor sit amet consectetur",
    description: "Lorem ipsum dolor sit amet consectetur",
    assignee: "Muhammed Usman",
    date: "May 29, 2023 @ 23:26:44",
    rule: "Enumaration of Users",
    severity: "low",
    type: "Malware Attack",
  },
  {
    id: 4,
    title: "test 4",
    details: "Lorem ipsum dolor sit amet consectetur",
    description: "Lorem ipsum dolor sit amet consectetur",
    assignee: "Joe Blue",
    date: "May 29, 2023 @ 23:26:44",
    rule: "Enumaration of Users",
    severity: "low",
    type: "Malware Attack",
  },
  {
    id: 5,
    title: "test 5",
    details: "Lorem ipsum dolor sit amet consectetur",
    description: "Lorem ipsum dolor sit amet consectetur",
    assignee: "Muhammed Umar",
    date: "May 29, 2023 @ 23:26:44",
    rule: "Enumaration of Users",
    severity: "low",
    type: "Malware Attack",
  },
  {
    id: 6,
    title: "test 6",
    details: "Lorem ipsum dolor sit amet consectetur",
    description: "Lorem ipsum dolor sit amet consectetur",
    assignee: "Furkan",
    date: "May 29, 2023 @ 23:26:44",
    rule: "Enumaration of Users",
    severity: "low",
    type: "Malware Attack",
  },
  {
    id: 7,
    title: "test 7",
    details: "Lorem ipsum dolor sit amet consectetur",
    description: "Lorem ipsum dolor sit amet consectetur",
    assignee: "Jason",
    date: "May 29, 2023 @ 23:26:44",
    rule: "Enumaration of Users",
    severity: "low",
    type: "Malware Attack",
  },
];

export default data;
